#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
filter=""
dry="0"
verbose="0"

cd "$script_dir"
scripts=$(find runs -maxdepth 1 -mindepth 1 -type f -perm -u=x)

while [[ $# > 0 ]]; do
    case "$1" in
        --dry)
            dry="1"
            ;;
        --verbose|-v)
            verbose="1"
            ;;
        *)
            filter="$1"
            ;;
    esac
    shift
done

export RUN_VERBOSE="$verbose"

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute: $@"
    if [[ $dry == "1" ]]; then
        return
    fi

    "$@"
}

log "run: filter=$filter"

for script in $scripts; do
    if echo "$script" | grep -qv -- "$filter"; then
        if [[ $dry == "1" ]]; then
            log "filtered: $filter -- $script"
        fi
        continue
    fi
    log "running script: $script"
    execute ./$script
done
