#!/usr/bin/env bash
set -euo pipefail
LOG_PREFIX="[tmux]"
source "$(dirname "$0")/_lib"

build_dir="$(mktemp -d)"
trap 'rm -rf "$build_dir"' EXIT
git clone -q --branch 3.5a --depth 1 https://github.com/tmux/tmux.git "$build_dir"
cd "$build_dir"

if [[ "$os_name" == "Darwin" ]]; then
  brew install -q automake pkg-config libevent ncurses utf8proc
  cores=$(sysctl -n hw.ncpu)
elif [[ "$os_name" == "Linux" ]]; then
  sudo apt-get update -qq
  sudo apt-get install -qq -y \
    libevent-dev \
    libncurses-dev \
    pkg-config \
    build-essential \
    automake \
    bison \
    libutf8proc-dev
  cores=$(nproc)
else
  log "Unknown OS: $os_name" >&2
  exit 1
fi

sh autogen.sh >/dev/null
./configure --enable-utf8proc >/dev/null && make -s -j"$cores"
sudo make -s install

mkdir -p ~/.tmux/plugins
if [[ ! -d ~/.tmux/plugins/tpm ]]; then
  git clone -q https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi
